### ISSUE TITLE
Include composer.lock file

### ISSUE THREAD

**Issue by chippyash** [Gregwar/Formidable#30]
You should include the composer.lock file in the repo.  That way, when end user does `composer install`  they will get the versions of dependencies that you used in the commit.

see [this article](https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file) on why composer.lock should be included.

Regards
A

**Comment by Gregwar** [comment]
I don't agree

1) Formidable will likely be used as a dependency of your own project, so what is the point of composer.lock in this case?
2) Popular contributions like Symfony and Laravel don't provide a composer.lock file
3) Versions tags are reliable enough to handle compatibility

The composer.lock is indeed really useful and should be commited in professional projects because it is a reassuring feature when deploying projects, but I don't think it's a good idea to put it in open source libraries

**Comment by chippyash** [comment]
The end user can always use `composer update` to break the dependency chain.  But you can guarantee that your library will work with the dependencies that you locked in.

I guess it is bit of a moot point when the only dependencies are of your own making, but when say, you depend on some third party library, I think it becomes more important to lock things down.

I did say 'should', not 'must', so your call.  :-)

**Comment by chippyash** [comment]
Closing this one.  I must have been having a bad day when I wrote the original post, because of course,what you say is correct. public lib => composer.lock bad, private lib => composer.lock good ;-)
